---
services:
  php:
    container_name: beets_php
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./src:/var/www/html
    ports:
      - 9000:80
    
  mysql_db:
    container_name: beets_mysql
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - beets_db_data:/var/lib/mysql
  
  phpmyadmin:
    container_name: beets_phpmyadmin
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  mailhog:
    container_name: beets_mailhog
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web interface

volumes:
  beets_db_data: