<?php partial('page-head'); ?>
<?php partial('sidebar'); ?>

<main class="bl__main">	
	<?php partial('navigation'); ?>

	<div class="bl__body container-xl px-sm-4">
		<h1 class="page-title"><?= $title ?></h1>
		<div class="card">
			<div class="card-body">
				<h2>Welcome to Beets PHP!</h2>
				<p class="fw-bold">Authenticated user: <?= \App\Models\User::fullName() ?></p>
				<p>This is a long text to demonstrate sticky header and sidebar behaviour:</p>
				<div class="ps-3 border-start text-secondary">
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
					<p class="mb-0">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit iusto nihil corrupti temporibus debitis ipsa modi accusantium similique nostrum laudantium dicta et earum ullam quaerat harum fuga, sapiente animi, mollitia iure libero. Alias, laborum? Neque, veniam quod. Laudantium est porro, vero itaque quasi doloribus voluptates odio dolorem totam consequuntur molestiae? Vel mollitia enim ad debitis hic qui perferendis et tenetur consequatur ipsam, tempore dolores ea blanditiis? Atque est accusantium quis, animi quisquam eligendi quidem delectus quaerat officia totam recusandae necessitatibus in facere laboriosam laudantium illum minus eaque optio similique quasi. Optio, odio aperiam dolores rem autem nam totam cum illum!</p>
				</div>
			</div>
		</div>
	</div>
</main>

<?php partial('page-foot'); ?>